### ISSUE TITLE
I can't open it.

### ISSUE THREAD

**Issue by charlie59876** [goph-R/TilePad#1]
![image](https://user-images.githubusercontent.com/38352981/64051418-f0501080-cb72-11e9-93bc-545596945d15.png)
When i open it i get this error. i tried everything. i reinstalled the program, i (re?)installed qt, still the same error. also i would like to know if you can remove padding from a pre-padded tileset with this?

**Comment by goph-R** [comment]
Hi!


Uh, sorry about that. Today I will upload the fixed version. I'm apologize
for that again.

Best wishes,
Gabor

**Comment by goph-R** [comment]
Please check the new release:
https://github.com/goph-R/TilePad/releases/tag/0.4.1

**Comment by goph-R** [comment]
No, currently you can't remove the padding, but it is a good idea, I can add it later.

**Comment by charlie59876** [comment]
> No, currently you can't remove the padding, but it is a good idea, I can add it later.

hey are you adding that? if so how long will it be? it's ok if ur not gonna i'd just like to know. it would be a very useful feature

**Comment by goph-R** [comment]
Yep, I'm added. Case closed :)
https://github.com/goph-R/TilePad/releases/tag/0.4.2

**Comment by goph-R** [comment]
You can use it via the "Remove padding" checkbox. After you checked, you can drop your padded image, then the result will be the original image.
